[package]

name = "html5ever"
version = "0.27.0"
authors = [ "The html5ever Project Developers" ]
license = "MIT OR Apache-2.0"
repository = "https://github.com/servo/html5ever"
description = "High-performance browser-grade HTML5 parser"
documentation = "https://docs.rs/html5ever"
categories = [ "parser-implementations", "web-programming" ]
edition = "2021"

[dependencies]
log = "0.4"
mac = "0.1"
markup5ever = { version = "0.12", path = "../markup5ever" }

[dev-dependencies]
criterion = "0.3"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["extra-traits", "full", "fold"] }
typed-arena = "2.0.2"

[[bench]]
name = "html5ever"
harness = false
